#!/bin/sh /etc/rc.common
# Place this script in /etc/init.d to autostart agetty using pl2303 detection
USE_PROCD=1
START=50
STOP=50
start_service() {
	if [ -z "$(/usr/sbin/getpl2303)" ]; then
		return
	fi 
	procd_open_instance
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_set_param command /usr/sbin/agetty 9600 $(/usr/sbin/getpl2303) dumb
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
        # wall "Terminal server is going DOWN for RESTART. Please log back in."
	stop
	start
}
